name: "PR Title Checker"
on:
  pull_request:
    types: [opened, reopened,edited]
    branches:
      - 'main'

permissions:
  pull-requests: write
  contents: write

jobs:
  pr_title_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull File
        run: |
          set -e
          echo "Starting the script..."
          git clone https://${{ secrets.PULL_FROM_OTHER_REPOSITORIES }}@github.com/roclub/workflow-templates.git source-repo
          cd source-repo
          echo "Printing the working directory..."
          pwd
          echo "Creating the destination directory (if it doesn't exist) and copying the config file..."
          mkdir -p ../.github/configs/
          cp -u .github/configs/pr-title-checker-config.json ../.github/configs/
          echo "The full file path of the copied pr-title-checker-config.json file is:"
          realpath ../.github/configs/pr-title-checker-config.json
          echo "Script ended."

      - name: Check PR title
        uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          local_configuration_path: .github/configs/pr-title-checker-config.json

      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prTitle = context.payload.pull_request.title;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The title of your PR '${prTitle}' is non-compliant to the conventions. Please refer to our [GitHub documentation in Notion](https://www.notion.so/roclub/Git-GitHub-GitFlow-85cbb825be004d4d8b8ff6c0fa12204b?pvs=4#47e4e0bd334a4b0da3f6f3ad33e4009a).`
            })
